import json
import os

def generate_summary():
    print("COMMUNICATION MODULE: Compiling the v1.0 Research Summary...")
    
    summary = "# UIL Autonomous Discovery Summary: v1.0\n"
    summary += "Generated by the MonongahelaHellbender Core\n\n"

    # 1. Batteries
    try:
        with open("discovery_report_v1.1.json", "r") as f:
            bat = json.load(f)
        summary += f"## 1. Energy Storage (Solid-State)\n- **Discovery:** {bat['primary_candidate']}\n- **Breakthrough:** {bat['metrics']['conductivity_rt']} (Superionic)\n\n"
    except: pass

    # 2. Carbon
    try:
        with open("carbon_capture/vetted_carbon_results.json", "r") as f:
            carbon = json.load(f)
        best_c = [c for c in carbon if c['final_verdict'] == "APPROVED"][0]
        summary += f"## 2. Carbon Capture (DAC)\n- **Discovery:** {best_c['formula']}\n- **Breakthrough:** {best_c['pore_space']} Å³/atom (Stabilized manifold)\n\n"
    except: pass

    # 3. Solar
    try:
        with open("Solar_Efficiency_UIL/adversarial/vetted_solar_results.json", "r") as f:
            solar = json.load(f)
        best_s = [s for s in solar if s['final_verdict'] == "APPROVED"][0]
        summary += f"## 3. Solar Efficiency\n- **Discovery:** {best_s['formula']}\n- **Breakthrough:** {best_s['band_gap']} eV (Shockley-Queisser optimized)\n\n"
    except: pass

    with open("RESEARCH_SUMMARY_v1.md", "w") as f:
        f.write(summary)
    print("SUCCESS: 'RESEARCH_SUMMARY_v1.md' has been generated.")

if __name__ == "__main__":
    generate_summary()
